import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  actions: {
    backgroundColor: '#fff',
    borderTopColor: '#e9ecef',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 20,
  },
  button: {
    alignItems: 'center',
    borderRadius: 12,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    paddingVertical: 16,
  },
  cardTitle: {
    color: '#212529',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 16,
  },
  cleanBadge: {
    backgroundColor: '#d1edff',
    borderColor: '#b3d9ff',
    borderWidth: 1,
  },
  closeButton: {
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
    borderRadius: 16,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  closeButtonText: {
    color: '#6c757d',
    fontSize: 20,
    fontWeight: 'bold',
  },
  container: {
    backgroundColor: '#f8f9fa',
    flex: 1,
  },
  content: {
    flex: 1,
  },
  geoTagContainer: {
    backgroundColor: '#f8f9fa',
    borderColor: '#e9ecef',
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 16,
    padding: 12,
  },
  geoTagLabel: {
    color: '#6c757d',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 4,
  },
  geoTagValue: {
    color: '#495057',
    fontFamily: 'monospace',
    fontSize: 11,
  },
  header: {
    alignItems: 'center',
    backgroundColor: '#fff',
    borderBottomColor: '#e9ecef',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  infoCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    elevation: 4,
    margin: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  infoLabel: {
    color: '#495057',
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
  },
  infoRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
    paddingVertical: 4,
  },
  infoValue: {
    color: '#212529',
    flex: 2,
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'right',
  },
  loadingSpinner: {
    marginRight: 8,
  },
  mockBadge: {
    backgroundColor: '#fff3cd',
    borderColor: '#ffeaa7',
    borderWidth: 1,
  },
  mockDetectionRow: {
    borderTopColor: '#e9ecef',
    borderTopWidth: 1,
    marginTop: 8,
    paddingTop: 12,
  },
  photo: {
    height: 300,
    width: '100%',
  },
  photoContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    elevation: 4,
    margin: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  retakeButton: {
    backgroundColor: '#6c757d',
  },
  retakeButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  statusBadge: {
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '600',
  },
  title: {
    color: '#212529',
    fontSize: 18,
    fontWeight: 'bold',
  },
  uploadButton: {
    backgroundColor: '#007AFF',
  },
  uploadButtonDisabled: {
    backgroundColor: '#c7c7cc',
  },
  uploadButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
});